# Generated by Django 3.2.16 on 2023-01-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, default='', max_length=39, verbose_name='GitHub username'),
        ),
    ]
