# Generated by Django 3.2.9 on 2022-03-06 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Order in which links will be presented on home page. The lower number the higher position.', verbose_name='order')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(unique=True)),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'front subpage',
                'verbose_name_plural': 'front subpages',
            },
        ),
        migrations.CreateModel(
            name='FrontPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Order in which links will be presented on home page. The lower number the higher position.', verbose_name='order')),
                ('text', models.TextField(verbose_name='text')),
                ('img', models.ImageField(upload_to='', verbose_name='image')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.frontpage')),
            ],
            options={
                'verbose_name': 'front subpage image',
                'verbose_name_plural': 'front subpage images',
            },
        ),
    ]
