# Generated by Django 3.2.16 on 2023-01-01 17:51

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='question')),
                ('order', models.IntegerField(default=0, help_text='Order in which links will be presented on home page. The lower number the higher position.', verbose_name='order')),
                ('answer', models.TextField(max_length=1000, verbose_name='answer')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='FrontLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='url')),
                ('type', models.IntegerField(choices=[(1, 'withoutAJAX'), (2, 'localWithAJAX')], help_text='"withoutAJAX" means standard link, "localWithAJAX" means local links accessible using AJAX technology', verbose_name='type')),
                ('icon', models.CharField(blank=True, help_text='Filename of icon from static/icon dir which will be presented on a card.', max_length=30, null=True, verbose_name='icon-name')),
                ('bgcolor', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None, verbose_name='bgcolor')),
                ('textcolor', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='textcolor')),
                ('order', models.IntegerField(default=0, help_text='Order in which links will be presented on home page. The lower number the higher position.', verbose_name='order')),
                ('title', models.CharField(default=None, max_length=30, verbose_name='title')),
                ('description', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'front link',
                'verbose_name_plural': 'front links',
            },
        ),
        migrations.CreateModel(
            name='DoorOpenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='request date')),
                ('succeeded', models.BooleanField(verbose_name='succeeded')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'door open request',
                'verbose_name_plural': 'door open requests',
            },
        ),
    ]
